### ISSUE TITLE
Selectors are not reliable

### ISSUE THREAD

**Issue by AdeelZahir** [zaidsoh/zameen-automated-tests#1]
@zaidsoh 

```
element :adultAddButton, :xpath, '//*[@id="FMP-target"]/div/div[1]/div/div/div/div/div[1]/div[2]/div/form/div[3]/div/div[2]/div/div/div[1]/div[1]/div/div/div/div[2]/div/div[3]/button'
```

Selectors like these won't last long. Even a slightest of the changes in the UI will break them.

This can be easily written as `//*[contains(@aria-labelledby,"adults")]//*[@aria-label="add"]`

You can read more about xpath axes from here:

https://www.w3schools.com/xml/xpath_axes.asp
https://www.javatpoint.com/xpath-axes

Can you update the selectors to use more from xpath axes?

**Comment by zaidsoh** [comment]
Resolved. Updated all unstable xpaths by using xpath axes instead
