### ISSUE TITLE
Search for properties that match the same filters as the first test.

### ISSUE THREAD

**Issue by AdeelZahir** [zaidsoh/zameen-automated-tests#2]
Hover over a given property.
Get all the properties displayed on the map and loop through them in order to find the one with the different color and same title as the hovered one (this is for assessment purposes, not real-life scenario).
Click the property from the map and open the details.
Verify that the details match the details from the search result.

**Comment by zaidsoh** [comment]
Related updated pushed. I have only verified the name, price and rating from the details.
